/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { InlineResponse20010 } from '../models';
import { InlineResponse2005 } from '../models';
import { InlineResponse2009 } from '../models';
/**
 * AddressesApi - axios parameter creator
 * @export
 */
export const AddressesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get balance by address.
         * @param {string} address Address
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1IndexerAddressAddressBalanceGet: async (address: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'address' is not null or undefined
            if (address === null || address === undefined) {
                throw new RequiredError('address','Required parameter address was null or undefined when calling v1IndexerAddressAddressBalanceGet.');
            }
            const localVarPath = `/v1/indexer/address/{address}/balance`
                .replace(`{${"address"}}`, encodeURIComponent(String(address)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get the tx history by address.
         * @param {string} address Address
         * @param {number} cursor Start offset
         * @param {number} size Number of items returned
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1IndexerAddressAddressHistoryGet: async (address: string, cursor: number, size: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'address' is not null or undefined
            if (address === null || address === undefined) {
                throw new RequiredError('address','Required parameter address was null or undefined when calling v1IndexerAddressAddressHistoryGet.');
            }
            // verify required parameter 'cursor' is not null or undefined
            if (cursor === null || cursor === undefined) {
                throw new RequiredError('cursor','Required parameter cursor was null or undefined when calling v1IndexerAddressAddressHistoryGet.');
            }
            // verify required parameter 'size' is not null or undefined
            if (size === null || size === undefined) {
                throw new RequiredError('size','Required parameter size was null or undefined when calling v1IndexerAddressAddressHistoryGet.');
            }
            const localVarPath = `/v1/indexer/address/{address}/history`
                .replace(`{${"address"}}`, encodeURIComponent(String(address)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get inscription UTXO list by address
         * @param {string} address Address
         * @param {number} cursor Start offset
         * @param {number} size Number of items returned
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1IndexerAddressAddressInscriptionUtxoDataGet: async (address: string, cursor: number, size: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'address' is not null or undefined
            if (address === null || address === undefined) {
                throw new RequiredError('address','Required parameter address was null or undefined when calling v1IndexerAddressAddressInscriptionUtxoDataGet.');
            }
            // verify required parameter 'cursor' is not null or undefined
            if (cursor === null || cursor === undefined) {
                throw new RequiredError('cursor','Required parameter cursor was null or undefined when calling v1IndexerAddressAddressInscriptionUtxoDataGet.');
            }
            // verify required parameter 'size' is not null or undefined
            if (size === null || size === undefined) {
                throw new RequiredError('size','Required parameter size was null or undefined when calling v1IndexerAddressAddressInscriptionUtxoDataGet.');
            }
            const localVarPath = `/v1/indexer/address/{address}/inscription-utxo-data`
                .replace(`{${"address"}}`, encodeURIComponent(String(address)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get non inscription UTXO list by address
         * @param {string} address Address
         * @param {number} cursor Start offset
         * @param {number} size Number of items returned
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1IndexerAddressAddressUtxoDataGet: async (address: string, cursor: number, size: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'address' is not null or undefined
            if (address === null || address === undefined) {
                throw new RequiredError('address','Required parameter address was null or undefined when calling v1IndexerAddressAddressUtxoDataGet.');
            }
            // verify required parameter 'cursor' is not null or undefined
            if (cursor === null || cursor === undefined) {
                throw new RequiredError('cursor','Required parameter cursor was null or undefined when calling v1IndexerAddressAddressUtxoDataGet.');
            }
            // verify required parameter 'size' is not null or undefined
            if (size === null || size === undefined) {
                throw new RequiredError('size','Required parameter size was null or undefined when calling v1IndexerAddressAddressUtxoDataGet.');
            }
            const localVarPath = `/v1/indexer/address/{address}/utxo-data`
                .replace(`{${"address"}}`, encodeURIComponent(String(address)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AddressesApi - functional programming interface
 * @export
 */
export const AddressesApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Get balance by address.
         * @param {string} address Address
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1IndexerAddressAddressBalanceGet(address: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse2009>>> {
            const localVarAxiosArgs = await AddressesApiAxiosParamCreator(configuration).v1IndexerAddressAddressBalanceGet(address, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get the tx history by address.
         * @param {string} address Address
         * @param {number} cursor Start offset
         * @param {number} size Number of items returned
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1IndexerAddressAddressHistoryGet(address: string, cursor: number, size: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse2005>>> {
            const localVarAxiosArgs = await AddressesApiAxiosParamCreator(configuration).v1IndexerAddressAddressHistoryGet(address, cursor, size, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get inscription UTXO list by address
         * @param {string} address Address
         * @param {number} cursor Start offset
         * @param {number} size Number of items returned
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1IndexerAddressAddressInscriptionUtxoDataGet(address: string, cursor: number, size: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse20010>>> {
            const localVarAxiosArgs = await AddressesApiAxiosParamCreator(configuration).v1IndexerAddressAddressInscriptionUtxoDataGet(address, cursor, size, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get non inscription UTXO list by address
         * @param {string} address Address
         * @param {number} cursor Start offset
         * @param {number} size Number of items returned
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1IndexerAddressAddressUtxoDataGet(address: string, cursor: number, size: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse20010>>> {
            const localVarAxiosArgs = await AddressesApiAxiosParamCreator(configuration).v1IndexerAddressAddressUtxoDataGet(address, cursor, size, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * AddressesApi - factory interface
 * @export
 */
export const AddressesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Get balance by address.
         * @param {string} address Address
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1IndexerAddressAddressBalanceGet(address: string, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse2009>> {
            return AddressesApiFp(configuration).v1IndexerAddressAddressBalanceGet(address, options).then((request) => request(axios, basePath));
        },
        /**
         * Get the tx history by address.
         * @param {string} address Address
         * @param {number} cursor Start offset
         * @param {number} size Number of items returned
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1IndexerAddressAddressHistoryGet(address: string, cursor: number, size: number, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse2005>> {
            return AddressesApiFp(configuration).v1IndexerAddressAddressHistoryGet(address, cursor, size, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get inscription UTXO list by address
         * @param {string} address Address
         * @param {number} cursor Start offset
         * @param {number} size Number of items returned
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1IndexerAddressAddressInscriptionUtxoDataGet(address: string, cursor: number, size: number, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse20010>> {
            return AddressesApiFp(configuration).v1IndexerAddressAddressInscriptionUtxoDataGet(address, cursor, size, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get non inscription UTXO list by address
         * @param {string} address Address
         * @param {number} cursor Start offset
         * @param {number} size Number of items returned
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1IndexerAddressAddressUtxoDataGet(address: string, cursor: number, size: number, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse20010>> {
            return AddressesApiFp(configuration).v1IndexerAddressAddressUtxoDataGet(address, cursor, size, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AddressesApi - object-oriented interface
 * @export
 * @class AddressesApi
 * @extends {BaseAPI}
 */
export class AddressesApi extends BaseAPI {
    /**
     * Get balance by address.
     * @param {string} address Address
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AddressesApi
     */
    public async v1IndexerAddressAddressBalanceGet(address: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse2009>> {
        return AddressesApiFp(this.configuration).v1IndexerAddressAddressBalanceGet(address, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get the tx history by address.
     * @param {string} address Address
     * @param {number} cursor Start offset
     * @param {number} size Number of items returned
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AddressesApi
     */
    public async v1IndexerAddressAddressHistoryGet(address: string, cursor: number, size: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse2005>> {
        return AddressesApiFp(this.configuration).v1IndexerAddressAddressHistoryGet(address, cursor, size, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get inscription UTXO list by address
     * @param {string} address Address
     * @param {number} cursor Start offset
     * @param {number} size Number of items returned
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AddressesApi
     */
    public async v1IndexerAddressAddressInscriptionUtxoDataGet(address: string, cursor: number, size: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse20010>> {
        return AddressesApiFp(this.configuration).v1IndexerAddressAddressInscriptionUtxoDataGet(address, cursor, size, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get non inscription UTXO list by address
     * @param {string} address Address
     * @param {number} cursor Start offset
     * @param {number} size Number of items returned
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AddressesApi
     */
    public async v1IndexerAddressAddressUtxoDataGet(address: string, cursor: number, size: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse20010>> {
        return AddressesApiFp(this.configuration).v1IndexerAddressAddressUtxoDataGet(address, cursor, size, options).then((request) => request(this.axios, this.basePath));
    }
}
