/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { InlineResponse20011 } from '../models';
import { InlineResponse20012 } from '../models';
/**
 * InscriptionsApi - axios parameter creator
 * @export
 */
export const InscriptionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get inscription content info by inscriptionId
         * @param {string} inscriptionid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1IndexerInscriptionContentInscriptionidGet: async (inscriptionid: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'inscriptionid' is not null or undefined
            if (inscriptionid === null || inscriptionid === undefined) {
                throw new RequiredError('inscriptionid','Required parameter inscriptionid was null or undefined when calling v1IndexerInscriptionContentInscriptionidGet.');
            }
            const localVarPath = `/v1/indexer/inscription/content/{inscriptionid}`
                .replace(`{${"inscriptionid"}}`, encodeURIComponent(String(inscriptionid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get inscription events
         * @param {number} start Start blockheight
         * @param {number} end End blockheight (0 represents the inclusion of mempool data.)
         * @param {number} cursor Start offset
         * @param {number} size Number of items returned
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1IndexerInscriptionEventsGet: async (start: number, end: number, cursor: number, size: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'start' is not null or undefined
            if (start === null || start === undefined) {
                throw new RequiredError('start','Required parameter start was null or undefined when calling v1IndexerInscriptionEventsGet.');
            }
            // verify required parameter 'end' is not null or undefined
            if (end === null || end === undefined) {
                throw new RequiredError('end','Required parameter end was null or undefined when calling v1IndexerInscriptionEventsGet.');
            }
            // verify required parameter 'cursor' is not null or undefined
            if (cursor === null || cursor === undefined) {
                throw new RequiredError('cursor','Required parameter cursor was null or undefined when calling v1IndexerInscriptionEventsGet.');
            }
            // verify required parameter 'size' is not null or undefined
            if (size === null || size === undefined) {
                throw new RequiredError('size','Required parameter size was null or undefined when calling v1IndexerInscriptionEventsGet.');
            }
            const localVarPath = `/v1/indexer/inscription/events`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (start !== undefined) {
                localVarQueryParameter['start'] = start;
            }

            if (end !== undefined) {
                localVarQueryParameter['end'] = end;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get inscription info by inscriptionId
         * @param {string} inscriptionid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1IndexerInscriptionInfoInscriptionidGet: async (inscriptionid: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'inscriptionid' is not null or undefined
            if (inscriptionid === null || inscriptionid === undefined) {
                throw new RequiredError('inscriptionid','Required parameter inscriptionid was null or undefined when calling v1IndexerInscriptionInfoInscriptionidGet.');
            }
            const localVarPath = `/v1/indexer/inscription/info/{inscriptionid}`
                .replace(`{${"inscriptionid"}}`, encodeURIComponent(String(inscriptionid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InscriptionsApi - functional programming interface
 * @export
 */
export const InscriptionsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Get inscription content info by inscriptionId
         * @param {string} inscriptionid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1IndexerInscriptionContentInscriptionidGet(inscriptionid: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await InscriptionsApiAxiosParamCreator(configuration).v1IndexerInscriptionContentInscriptionidGet(inscriptionid, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get inscription events
         * @param {number} start Start blockheight
         * @param {number} end End blockheight (0 represents the inclusion of mempool data.)
         * @param {number} cursor Start offset
         * @param {number} size Number of items returned
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1IndexerInscriptionEventsGet(start: number, end: number, cursor: number, size: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse20012>>> {
            const localVarAxiosArgs = await InscriptionsApiAxiosParamCreator(configuration).v1IndexerInscriptionEventsGet(start, end, cursor, size, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get inscription info by inscriptionId
         * @param {string} inscriptionid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1IndexerInscriptionInfoInscriptionidGet(inscriptionid: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse20011>>> {
            const localVarAxiosArgs = await InscriptionsApiAxiosParamCreator(configuration).v1IndexerInscriptionInfoInscriptionidGet(inscriptionid, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * InscriptionsApi - factory interface
 * @export
 */
export const InscriptionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Get inscription content info by inscriptionId
         * @param {string} inscriptionid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1IndexerInscriptionContentInscriptionidGet(inscriptionid: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return InscriptionsApiFp(configuration).v1IndexerInscriptionContentInscriptionidGet(inscriptionid, options).then((request) => request(axios, basePath));
        },
        /**
         * Get inscription events
         * @param {number} start Start blockheight
         * @param {number} end End blockheight (0 represents the inclusion of mempool data.)
         * @param {number} cursor Start offset
         * @param {number} size Number of items returned
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1IndexerInscriptionEventsGet(start: number, end: number, cursor: number, size: number, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse20012>> {
            return InscriptionsApiFp(configuration).v1IndexerInscriptionEventsGet(start, end, cursor, size, options).then((request) => request(axios, basePath));
        },
        /**
         * Get inscription info by inscriptionId
         * @param {string} inscriptionid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1IndexerInscriptionInfoInscriptionidGet(inscriptionid: string, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse20011>> {
            return InscriptionsApiFp(configuration).v1IndexerInscriptionInfoInscriptionidGet(inscriptionid, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InscriptionsApi - object-oriented interface
 * @export
 * @class InscriptionsApi
 * @extends {BaseAPI}
 */
export class InscriptionsApi extends BaseAPI {
    /**
     * Get inscription content info by inscriptionId
     * @param {string} inscriptionid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InscriptionsApi
     */
    public async v1IndexerInscriptionContentInscriptionidGet(inscriptionid: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return InscriptionsApiFp(this.configuration).v1IndexerInscriptionContentInscriptionidGet(inscriptionid, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get inscription events
     * @param {number} start Start blockheight
     * @param {number} end End blockheight (0 represents the inclusion of mempool data.)
     * @param {number} cursor Start offset
     * @param {number} size Number of items returned
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InscriptionsApi
     */
    public async v1IndexerInscriptionEventsGet(start: number, end: number, cursor: number, size: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse20012>> {
        return InscriptionsApiFp(this.configuration).v1IndexerInscriptionEventsGet(start, end, cursor, size, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get inscription info by inscriptionId
     * @param {string} inscriptionid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InscriptionsApi
     */
    public async v1IndexerInscriptionInfoInscriptionidGet(inscriptionid: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse20011>> {
        return InscriptionsApiFp(this.configuration).v1IndexerInscriptionInfoInscriptionidGet(inscriptionid, options).then((request) => request(this.axios, this.basePath));
    }
}
