/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { InlineResponse2006 } from '../models';
import { InlineResponse2007 } from '../models';
import { InlineResponse2008 } from '../models';
/**
 * TransactionsApi - axios parameter creator
 * @export
 */
export const TransactionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get the summary info of a tx.
         * @param {string} txid Tx id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1IndexerTxTxidGet: async (txid: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'txid' is not null or undefined
            if (txid === null || txid === undefined) {
                throw new RequiredError('txid','Required parameter txid was null or undefined when calling v1IndexerTxTxidGet.');
            }
            const localVarPath = `/v1/indexer/tx/{txid}`
                .replace(`{${"txid"}}`, encodeURIComponent(String(txid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get the inputs of a tx.
         * @param {string} txid Tx id
         * @param {number} cursor Start offset
         * @param {number} size Number of items returned
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1IndexerTxTxidInsGet: async (txid: string, cursor: number, size: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'txid' is not null or undefined
            if (txid === null || txid === undefined) {
                throw new RequiredError('txid','Required parameter txid was null or undefined when calling v1IndexerTxTxidInsGet.');
            }
            // verify required parameter 'cursor' is not null or undefined
            if (cursor === null || cursor === undefined) {
                throw new RequiredError('cursor','Required parameter cursor was null or undefined when calling v1IndexerTxTxidInsGet.');
            }
            // verify required parameter 'size' is not null or undefined
            if (size === null || size === undefined) {
                throw new RequiredError('size','Required parameter size was null or undefined when calling v1IndexerTxTxidInsGet.');
            }
            const localVarPath = `/v1/indexer/tx/{txid}/ins`
                .replace(`{${"txid"}}`, encodeURIComponent(String(txid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get the outputs of a tx.
         * @param {string} txid Tx id
         * @param {number} cursor Start offset
         * @param {number} size Number of items returned
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1IndexerTxTxidOutsGet: async (txid: string, cursor: number, size: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'txid' is not null or undefined
            if (txid === null || txid === undefined) {
                throw new RequiredError('txid','Required parameter txid was null or undefined when calling v1IndexerTxTxidOutsGet.');
            }
            // verify required parameter 'cursor' is not null or undefined
            if (cursor === null || cursor === undefined) {
                throw new RequiredError('cursor','Required parameter cursor was null or undefined when calling v1IndexerTxTxidOutsGet.');
            }
            // verify required parameter 'size' is not null or undefined
            if (size === null || size === undefined) {
                throw new RequiredError('size','Required parameter size was null or undefined when calling v1IndexerTxTxidOutsGet.');
            }
            const localVarPath = `/v1/indexer/tx/{txid}/outs`
                .replace(`{${"txid"}}`, encodeURIComponent(String(txid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TransactionsApi - functional programming interface
 * @export
 */
export const TransactionsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Get the summary info of a tx.
         * @param {string} txid Tx id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1IndexerTxTxidGet(txid: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse2006>>> {
            const localVarAxiosArgs = await TransactionsApiAxiosParamCreator(configuration).v1IndexerTxTxidGet(txid, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get the inputs of a tx.
         * @param {string} txid Tx id
         * @param {number} cursor Start offset
         * @param {number} size Number of items returned
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1IndexerTxTxidInsGet(txid: string, cursor: number, size: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse2007>>> {
            const localVarAxiosArgs = await TransactionsApiAxiosParamCreator(configuration).v1IndexerTxTxidInsGet(txid, cursor, size, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get the outputs of a tx.
         * @param {string} txid Tx id
         * @param {number} cursor Start offset
         * @param {number} size Number of items returned
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1IndexerTxTxidOutsGet(txid: string, cursor: number, size: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse2008>>> {
            const localVarAxiosArgs = await TransactionsApiAxiosParamCreator(configuration).v1IndexerTxTxidOutsGet(txid, cursor, size, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * TransactionsApi - factory interface
 * @export
 */
export const TransactionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Get the summary info of a tx.
         * @param {string} txid Tx id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1IndexerTxTxidGet(txid: string, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse2006>> {
            return TransactionsApiFp(configuration).v1IndexerTxTxidGet(txid, options).then((request) => request(axios, basePath));
        },
        /**
         * Get the inputs of a tx.
         * @param {string} txid Tx id
         * @param {number} cursor Start offset
         * @param {number} size Number of items returned
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1IndexerTxTxidInsGet(txid: string, cursor: number, size: number, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse2007>> {
            return TransactionsApiFp(configuration).v1IndexerTxTxidInsGet(txid, cursor, size, options).then((request) => request(axios, basePath));
        },
        /**
         * Get the outputs of a tx.
         * @param {string} txid Tx id
         * @param {number} cursor Start offset
         * @param {number} size Number of items returned
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1IndexerTxTxidOutsGet(txid: string, cursor: number, size: number, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse2008>> {
            return TransactionsApiFp(configuration).v1IndexerTxTxidOutsGet(txid, cursor, size, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TransactionsApi - object-oriented interface
 * @export
 * @class TransactionsApi
 * @extends {BaseAPI}
 */
export class TransactionsApi extends BaseAPI {
    /**
     * Get the summary info of a tx.
     * @param {string} txid Tx id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApi
     */
    public async v1IndexerTxTxidGet(txid: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse2006>> {
        return TransactionsApiFp(this.configuration).v1IndexerTxTxidGet(txid, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get the inputs of a tx.
     * @param {string} txid Tx id
     * @param {number} cursor Start offset
     * @param {number} size Number of items returned
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApi
     */
    public async v1IndexerTxTxidInsGet(txid: string, cursor: number, size: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse2007>> {
        return TransactionsApiFp(this.configuration).v1IndexerTxTxidInsGet(txid, cursor, size, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get the outputs of a tx.
     * @param {string} txid Tx id
     * @param {number} cursor Start offset
     * @param {number} size Number of items returned
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApi
     */
    public async v1IndexerTxTxidOutsGet(txid: string, cursor: number, size: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse2008>> {
        return TransactionsApiFp(this.configuration).v1IndexerTxTxidOutsGet(txid, cursor, size, options).then((request) => request(this.axios, this.basePath));
    }
}
