/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { V3markettypeauctionactionsFilter } from './v3markettypeauctionactions-filter';
import {
    V3markettypeauctionactionsFilter,
} from ".";

/**
 * 
 *
 * @export
 * @interface AuctionActionsBody
 */
export interface AuctionActionsBody {

    /**
     * @type {V3markettypeauctionactionsFilter}
     * @memberof AuctionActionsBody
     */
    filter: V3markettypeauctionactionsFilter;

    /**
     * @type {number}
     * @memberof AuctionActionsBody
     */
    start: number;

    /**
     * @type {number}
     * @memberof AuctionActionsBody
     */
    limit: number;
}
