/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface AuctionCreatePutOnBody
 */
export interface AuctionCreatePutOnBody {

    /**
     * @type {string}
     * @memberof AuctionCreatePutOnBody
     */
    inscriptionId: string;

    /**
     * Set the initial total price
     *
     * @type {string}
     * @memberof AuctionCreatePutOnBody
     */
    initPrice: string;

    /**
     * Unit Price (for tick)
     *
     * @type {string}
     * @memberof AuctionCreatePutOnBody
     */
    unitPrice: string;

    /**
     * User public key
     *
     * @type {string}
     * @memberof AuctionCreatePutOnBody
     */
    pubkey: string;

    /**
     * @type {string}
     * @memberof AuctionCreatePutOnBody
     * @example fixedPrice
     */
    marketType: AuctionCreatePutOnBodyMarketTypeEnum;

    /**
     * Auction mode optional, setting time of the order
     *
     * @type {number}
     * @memberof AuctionCreatePutOnBody
     */
    auctionTime?: number;

    /**
     * Auction mode optional, setting max price of the order
     *
     * @type {string}
     * @memberof AuctionCreatePutOnBody
     */
    maxPrice?: string;

    /**
     * (Optional) Only for multi-address wallet, such as Xverse, hiro. Specifies the BTC receive address
     *
     * @type {string}
     * @memberof AuctionCreatePutOnBody
     */
    btcAddress?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum AuctionCreatePutOnBodyMarketTypeEnum {
    Auction = 'auction',
    FixedPrice = 'fixedPrice'
}

