/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface AuctionBrc20KlineBody
 */
export interface AuctionBrc20KlineBody {

    /**
     * @type {string}
     * @memberof AuctionBrc20KlineBody
     */
    tick: string;

    /**
     * Start time range
     *
     * @type {number}
     * @memberof AuctionBrc20KlineBody
     */
    timeStart: number;

    /**
     * End time range
     *
     * @type {number}
     * @memberof AuctionBrc20KlineBody
     */
    timeEnd: number;

    /**
     * Time granularity, such as milliseconds for a 5-minute interval
     *
     * @type {number}
     * @memberof AuctionBrc20KlineBody
     */
    timeStep: number;
}
