/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface AuctionCreateBidBody
 */
export interface AuctionCreateBidBody {

    /**
     * @type {string}
     * @memberof AuctionCreateBidBody
     */
    auctionId: string;

    /**
     * @type {number}
     * @memberof AuctionCreateBidBody
     */
    bidPrice: number;

    /**
     * Bidder address
     *
     * @type {string}
     * @memberof AuctionCreateBidBody
     */
    address: string;

    /**
     * Bidder pubkey
     *
     * @type {string}
     * @memberof AuctionCreateBidBody
     */
    pubkey: string;

    /**
     * The user sets the rate
     *
     * @type {number}
     * @memberof AuctionCreateBidBody
     */
    feeRate?: number;

    /**
     * (Optional) Only for multi-address wallet, such as Xverse, hiro. Inscription receiving address
     *
     * @type {string}
     * @memberof AuctionCreateBidBody
     */
    nftAddress?: string;
}
