/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface AuctionConfirmBidBody
 */
export interface AuctionConfirmBidBody {

    /**
     * @type {string}
     * @memberof AuctionConfirmBidBody
     */
    auctionId: string;

    /**
     * @type {string}
     * @memberof AuctionConfirmBidBody
     */
    bidId: string;

    /**
     * @type {string}
     * @memberof AuctionConfirmBidBody
     */
    psbtBid: string;

    /**
     * Auction mode is used, and the current empty string can be passed
     *
     * @type {string}
     * @memberof AuctionConfirmBidBody
     */
    psbtBid2: string;

    /**
     * Auction mode is used, and the current empty string can be passed
     *
     * @type {string}
     * @memberof AuctionConfirmBidBody
     */
    psbtSettle: string;

    /**
     * Is Base64 format, the default is hex format
     *
     * @type {boolean}
     * @memberof AuctionConfirmBidBody
     */
    fromBase64?: boolean;
}
