/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface AuctionCreatePutOffBody
 */
export interface AuctionCreatePutOffBody {

    /**
     * @type {string}
     * @memberof AuctionCreatePutOffBody
     */
    auctionId: string;

    /**
     * (Optional) Only for multi-address wallet, such as Xverse, hiro. Inscription receiving address.
     *
     * @type {string}
     * @memberof AuctionCreatePutOffBody
     */
    nftAddress?: string;

    /**
     * (Optional) Only for multi-address wallet, such as Xverse, hiro. The public key used in the inscription of the order.
     *
     * @type {string}
     * @memberof AuctionCreatePutOffBody
     */
    btcPubkey?: string;
}
