/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface Brc20swapSwapBody
 */
export interface Brc20swapSwapBody {

    /**
     * @type {string}
     * @memberof Brc20swapSwapBody
     */
    address: string;

    /**
     * Input tick
     *
     * @type {string}
     * @memberof Brc20swapSwapBody
     */
    tickIn: string;

    /**
     * Output tick
     *
     * @type {string}
     * @memberof Brc20swapSwapBody
     */
    tickOut: string;

    /**
     * The amount of input tick
     *
     * @type {string}
     * @memberof Brc20swapSwapBody
     */
    amountIn: string;

    /**
     * The amount of output tick
     *
     * @type {string}
     * @memberof Brc20swapSwapBody
     */
    amountOut: string;

    /**
     * @type {string}
     * @memberof Brc20swapSwapBody
     */
    slippage: string;

    /**
     * @type {string}
     * @memberof Brc20swapSwapBody
     */
    exactType: Brc20swapSwapBodyExactTypeEnum;

    /**
     * Timestamp (seconds)
     *
     * @type {number}
     * @memberof Brc20swapSwapBody
     */
    ts: number;

    /**
     * User signature
     *
     * @type {string}
     * @memberof Brc20swapSwapBody
     */
    sig: string;
}

/**
 * @export
 * @enum {string}
 */
export enum Brc20swapSwapBodyExactTypeEnum {
    ExactIn = 'exactIn',
    ExactOut = 'exactOut'
}

