/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface BRC20InfoItem
 */
export interface BRC20InfoItem {

    /**
     * @type {string}
     * @memberof BRC20InfoItem
     */
    ticker?: string;

    /**
     * @type {string}
     * @memberof BRC20InfoItem
     */
    creator?: string;

    /**
     * @type {string}
     * @memberof BRC20InfoItem
     */
    totalMinted?: string;

    /**
     * @type {string}
     * @memberof BRC20InfoItem
     */
    confirmedMinted?: string;

    /**
     * @type {string}
     * @memberof BRC20InfoItem
     */
    confirmedMinted1h?: string;

    /**
     * @type {string}
     * @memberof BRC20InfoItem
     */
    confirmedMinted24h?: string;

    /**
     * @type {number}
     * @memberof BRC20InfoItem
     */
    completeBlocktime?: number;

    /**
     * @type {number}
     * @memberof BRC20InfoItem
     */
    completeHeight?: number;

    /**
     * @type {number}
     * @memberof BRC20InfoItem
     */
    inscriptionNumberEnd?: number;

    /**
     * @type {number}
     * @memberof BRC20InfoItem
     */
    inscriptionNumberStart?: number;

    /**
     * @type {string}
     * @memberof BRC20InfoItem
     */
    minted?: string;

    /**
     * @type {number}
     * @memberof BRC20InfoItem
     */
    mintTimes?: number;

    /**
     * @type {number}
     * @memberof BRC20InfoItem
     */
    historyCount?: number;

    /**
     * @type {number}
     * @memberof BRC20InfoItem
     */
    holdersCount?: number;

    /**
     * @type {string}
     * @memberof BRC20InfoItem
     */
    txid?: string;

    /**
     * @type {number}
     * @memberof BRC20InfoItem
     */
    deployHeight?: number;

    /**
     * @type {number}
     * @memberof BRC20InfoItem
     */
    deployBlocktime?: number;

    /**
     * @type {string}
     * @memberof BRC20InfoItem
     */
    inscriptionId?: string;

    /**
     * @type {number}
     * @memberof BRC20InfoItem
     */
    inscriptionNumber?: number;

    /**
     * @type {string}
     * @memberof BRC20InfoItem
     */
    max?: string;

    /**
     * @type {number}
     * @memberof BRC20InfoItem
     */
    decimal?: number;

    /**
     * @type {string}
     * @memberof BRC20InfoItem
     */
    limit?: string;
}
