/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface BRC20HistoryItem
 */
export interface BRC20HistoryItem {

    /**
     * @type {boolean}
     * @memberof BRC20HistoryItem
     */
    valid?: boolean;

    /**
     * @type {string}
     * @memberof BRC20HistoryItem
     */
    type?: string;

    /**
     * @type {string}
     * @memberof BRC20HistoryItem
     */
    from?: string;

    /**
     * @type {string}
     * @memberof BRC20HistoryItem
     */
    to?: string;

    /**
     * @type {string}
     * @memberof BRC20HistoryItem
     */
    amount?: string;

    /**
     * @type {string}
     * @memberof BRC20HistoryItem
     */
    overallBalance?: string;

    /**
     * @type {string}
     * @memberof BRC20HistoryItem
     */
    availableBalance?: string;

    /**
     * @type {string}
     * @memberof BRC20HistoryItem
     */
    transferBalance?: string;

    /**
     * @type {string}
     * @memberof BRC20HistoryItem
     */
    inscriptionId?: string;

    /**
     * @type {number}
     * @memberof BRC20HistoryItem
     */
    inscriptionNumber?: number;

    /**
     * @type {number}
     * @memberof BRC20HistoryItem
     */
    height?: number;

    /**
     * @type {string}
     * @memberof BRC20HistoryItem
     */
    blockhash?: string;

    /**
     * @type {number}
     * @memberof BRC20HistoryItem
     */
    blocktime?: number;

    /**
     * @type {number}
     * @memberof BRC20HistoryItem
     */
    txIdx?: number;

    /**
     * @type {string}
     * @memberof BRC20HistoryItem
     */
    txid?: string;

    /**
     * @type {number}
     * @memberof BRC20HistoryItem
     */
    satoshi?: number;

    /**
     * @type {number}
     * @memberof BRC20HistoryItem
     */
    offset?: number;
}
