/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface Brc20swapAddLiqBody
 */
export interface Brc20swapAddLiqBody {

    /**
     * @type {string}
     * @memberof Brc20swapAddLiqBody
     */
    address: string;

    /**
     * @type {string}
     * @memberof Brc20swapAddLiqBody
     */
    tick0: string;

    /**
     * @type {string}
     * @memberof Brc20swapAddLiqBody
     */
    tick1: string;

    /**
     * Input amount of tick0
     *
     * @type {string}
     * @memberof Brc20swapAddLiqBody
     */
    amount0: string;

    /**
     * Input amount of tick1
     *
     * @type {string}
     * @memberof Brc20swapAddLiqBody
     */
    amount1: string;

    /**
     * @type {string}
     * @memberof Brc20swapAddLiqBody
     */
    lp: string;

    /**
     * @type {string}
     * @memberof Brc20swapAddLiqBody
     */
    slippage: string;

    /**
     * Timestamp (seconds)
     *
     * @type {number}
     * @memberof Brc20swapAddLiqBody
     */
    ts: number;

    /**
     * User signature
     *
     * @type {string}
     * @memberof Brc20swapAddLiqBody
     */
    sig: string;
}
