/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse2003Data } from './inline-response2003-data';
import {
    InlineResponse2003Data,
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse2003
 */
export interface InlineResponse2003 {

    /**
     * @type {number}
     * @memberof InlineResponse2003
     */
    code?: InlineResponse2003CodeEnum;

    /**
     * @type {string}
     * @memberof InlineResponse2003
     * @example OK
     */
    msg?: string;

    /**
     * @type {InlineResponse2003Data}
     * @memberof InlineResponse2003
     */
    data?: InlineResponse2003Data;
}

/**
 * @export
 * @enum {string}
 */
export enum InlineResponse2003CodeEnum {
    NUMBER_0 = 0,
    NUMBER_MINUS_1 = -1
}

