/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse2004Data
 */
export interface InlineResponse2004Data {

    /**
     * @type {string}
     * @memberof InlineResponse2004Data
     */
    chain?: string;

    /**
     * @type {number}
     * @memberof InlineResponse2004Data
     */
    blocks?: number;

    /**
     * @type {number}
     * @memberof InlineResponse2004Data
     */
    headers?: number;

    /**
     * @type {string}
     * @memberof InlineResponse2004Data
     */
    bestBlockHash?: string;

    /**
     * @type {string}
     * @memberof InlineResponse2004Data
     */
    prevBlockHash?: string;

    /**
     * @type {number}
     * @memberof InlineResponse2004Data
     */
    medianTime?: number;

    /**
     * @type {string}
     * @memberof InlineResponse2004Data
     */
    chainwork?: string;
}
