/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse20041DataList
 */
export interface InlineResponse20041DataList {

    /**
     * @type {string}
     * @memberof InlineResponse20041DataList
     */
    txid?: string;

    /**
     * @type {number}
     * @memberof InlineResponse20041DataList
     */
    height?: number;

    /**
     * Number of transactions in the inscription
     *
     * @type {number}
     * @memberof InlineResponse20041DataList
     */
    transactionNum?: number;

    /**
     * Rollup inscription id
     *
     * @type {string}
     * @memberof InlineResponse20041DataList
     */
    inscriptionId?: string;

    /**
     * Rollup inscription number
     *
     * @type {number}
     * @memberof InlineResponse20041DataList
     */
    inscriptionNumber?: number;

    /**
     * @type {number}
     * @memberof InlineResponse20041DataList
     */
    ts?: number;
}
