/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse20022DataDetailData } from './inline-response20022-data-detail-data';
import {
    InlineResponse20022DataDetailData,
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse20022DataDetail
 */
export interface InlineResponse20022DataDetail {

    /**
     * @type {number}
     * @memberof InlineResponse20022DataDetail
     */
    confirmations?: number;

    /**
     * @type {InlineResponse20022DataDetailData}
     * @memberof InlineResponse20022DataDetail
     */
    data?: InlineResponse20022DataDetailData;
}
