/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse20045DataList
 */
export interface InlineResponse20045DataList {

    /**
     * @type {string}
     * @memberof InlineResponse20045DataList
     */
    id?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20045DataList
     */
    tick?: string;

    /**
     * Total amount withdrawal
     *
     * @type {string}
     * @memberof InlineResponse20045DataList
     */
    totalAmount?: string;

    /**
     * The number of withdrawal completed
     *
     * @type {string}
     * @memberof InlineResponse20045DataList
     */
    completedAmount?: string;

    /**
     * @type {number}
     * @memberof InlineResponse20045DataList
     */
    ts?: number;

    /**
     * The current number of confirmations
     *
     * @type {number}
     * @memberof InlineResponse20045DataList
     */
    totalConfirmedNum?: number;

    /**
     * The total number of confirmations
     *
     * @type {number}
     * @memberof InlineResponse20045DataList
     */
    totalNum?: number;

    /**
     * @type {string}
     * @memberof InlineResponse20045DataList
     */
    status?: string;
}
