/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BRC20HistoryInscription } from './brc20-history-inscription';
import {
    BRC20HistoryInscription,
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse20021Data
 */
export interface InlineResponse20021Data {

    /**
     * @type {string}
     * @memberof InlineResponse20021Data
     */
    ticker?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20021Data
     */
    overallBalance?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20021Data
     */
    availableBalance?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20021Data
     */
    availableBalanceSafe?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20021Data
     */
    availableBalanceUnSafe?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20021Data
     */
    transferableBalance?: string;

    /**
     * @type {number}
     * @memberof InlineResponse20021Data
     */
    historyCount?: number;

    /**
     * @type {Array<BRC20HistoryInscription>}
     * @memberof InlineResponse20021Data
     */
    historyInscriptions?: Array<BRC20HistoryInscription>;

    /**
     * @type {number}
     * @memberof InlineResponse20021Data
     */
    transferableCount?: number;

    /**
     * @type {Array<BRC20HistoryInscription>}
     * @memberof InlineResponse20021Data
     */
    transferableInscriptions?: Array<BRC20HistoryInscription>;
}
