/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Order } from './order';
import {
    Order,
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse2001
 */
export interface InlineResponse2001 {

    /**
     * @type {number}
     * @memberof InlineResponse2001
     */
    code?: number;

    /**
     * @type {string}
     * @memberof InlineResponse2001
     */
    msg?: string;

    /**
     * @type {Order}
     * @memberof InlineResponse2001
     */
    data?: Order;
}
