/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse20052DataList
 */
export interface InlineResponse20052DataList {

    /**
     * @type {string}
     * @memberof InlineResponse20052DataList
     */
    auctionId?: string | null;

    /**
     * @type {string}
     * @memberof InlineResponse20052DataList
     */
    inscriptionId: string;

    /**
     * @type {number}
     * @memberof InlineResponse20052DataList
     */
    inscriptionNumber?: number | null;

    /**
     * @type {string}
     * @memberof InlineResponse20052DataList
     */
    marketType?: string | null;

    /**
     * @type {string}
     * @memberof InlineResponse20052DataList
     */
    address?: string | null;

    /**
     * @type {number}
     * @memberof InlineResponse20052DataList
     */
    price?: number | null;

    /**
     * Domain name content support on sale
     *
     * @type {boolean}
     * @memberof InlineResponse20052DataList
     */
    notSupport?: boolean;

    /**
     * Whether the collection is validated
     *
     * @type {boolean}
     * @memberof InlineResponse20052DataList
     */
    verification?: boolean;

    /**
     * @type {string}
     * @memberof InlineResponse20052DataList
     */
    nftType?: string | null;

    /**
     * Brc20 field
     *
     * @type {string}
     * @memberof InlineResponse20052DataList
     */
    tick?: string | null;

    /**
     * Brc20 field
     *
     * @type {number}
     * @memberof InlineResponse20052DataList
     */
    limit?: number | null;

    /**
     * Brc20 field
     *
     * @type {number}
     * @memberof InlineResponse20052DataList
     */
    amount?: number | null;

    /**
     * Brc20 field
     *
     * @type {number}
     * @memberof InlineResponse20052DataList
     */
    unitPrice?: number | null;

    /**
     * Collection field
     *
     * @type {string}
     * @memberof InlineResponse20052DataList
     */
    collectionId?: string | null;

    /**
     * Collection field
     *
     * @type {string}
     * @memberof InlineResponse20052DataList
     */
    contentType?: string | null;

    /**
     * Collection field
     *
     * @type {string}
     * @memberof InlineResponse20052DataList
     */
    contentBody?: string | null;

    /**
     * Collection field
     *
     * @type {string}
     * @memberof InlineResponse20052DataList
     */
    collectionItemName?: string | null;

    /**
     * Collection field
     *
     * @type {string}
     * @memberof InlineResponse20052DataList
     */
    collectionHighResImgUrl?: string | null;

    /**
     * Collection field
     *
     * @type {string}
     * @memberof InlineResponse20052DataList
     */
    collectionName?: string | null;

    /**
     * Collection field
     *
     * @type {boolean}
     * @memberof InlineResponse20052DataList
     */
    notOnSale?: boolean | null;

    /**
     * Domain field
     *
     * @type {string}
     * @memberof InlineResponse20052DataList
     */
    domain?: string | null;

    /**
     * Domain field
     *
     * @type {string}
     * @memberof InlineResponse20052DataList
     */
    domainHex?: string | null;

    /**
     * Domain field
     *
     * @type {string}
     * @memberof InlineResponse20052DataList
     */
    domainType?: InlineResponse20052DataListDomainTypeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum InlineResponse20052DataListDomainTypeEnum {
    Sats = 'sats',
    Unisat = 'unisat',
    Btc = 'btc',
    Xbt = 'xbt',
    Ord = 'ord',
    Gm = 'gm',
    Bitmap = 'bitmap',
    X = 'x',
    Null = 'null'
}

