/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse20017DataDetail } from './inline-response20017-data-detail';
import {
    InlineResponse20017DataDetail,
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse20017Data
 */
export interface InlineResponse20017Data {

    /**
     * @type {Array<InlineResponse20017DataDetail>}
     * @memberof InlineResponse20017Data
     */
    detail?: Array<InlineResponse20017DataDetail>;

    /**
     * @type {number}
     * @memberof InlineResponse20017Data
     */
    start?: number;

    /**
     * @type {number}
     * @memberof InlineResponse20017Data
     */
    total?: number;
}
