/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InscriptionEvent } from './inscription-event';
import {
    InscriptionEvent,
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse20012Data
 */
export interface InlineResponse20012Data {

    /**
     * @type {number}
     * @memberof InlineResponse20012Data
     */
    cursor?: number;

    /**
     * @type {number}
     * @memberof InlineResponse20012Data
     */
    total?: number;

    /**
     * @type {Array<InscriptionEvent>}
     * @memberof InlineResponse20012Data
     */
    detail?: Array<InscriptionEvent>;
}
