/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse20026Data } from './inline-response20026-data';
import {
    InlineResponse20026Data,
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse20026
 */
export interface InlineResponse20026 {

    /**
     * @type {number}
     * @memberof InlineResponse20026
     */
    code: number;

    /**
     * @type {string}
     * @memberof InlineResponse20026
     */
    msg: string;

    /**
     * @type {Array<InlineResponse20026Data>}
     * @memberof InlineResponse20026
     */
    data: Array<InlineResponse20026Data>;
}
