/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TxHistoryItem } from './tx-history-item';
import {
    TxHistoryItem,
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse2005Data
 */
export interface InlineResponse2005Data {

    /**
     * @type {Array<TxHistoryItem>}
     * @memberof InlineResponse2005Data
     */
    detail?: Array<TxHistoryItem>;

    /**
     * @type {number}
     * @memberof InlineResponse2005Data
     */
    start?: number;

    /**
     * @type {number}
     * @memberof InlineResponse2005Data
     */
    total?: number;
}
