/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse20019Data } from './inline-response20019-data';
import {
    InlineResponse20019Data,
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse20019
 */
export interface InlineResponse20019 {

    /**
     * @type {number}
     * @memberof InlineResponse20019
     */
    code?: InlineResponse20019CodeEnum;

    /**
     * @type {string}
     * @memberof InlineResponse20019
     * @example OK
     */
    msg?: string;

    /**
     * @type {InlineResponse20019Data}
     * @memberof InlineResponse20019
     */
    data?: InlineResponse20019Data;
}

/**
 * @export
 * @enum {string}
 */
export enum InlineResponse20019CodeEnum {
    NUMBER_0 = 0,
    NUMBER_MINUS_1 = -1
}

