/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse20011DataBrc20 } from './inline-response20011-data-brc20';
import { InlineResponse20011DataUtxo } from './inline-response20011-data-utxo';
import {
    InlineResponse20011DataBrc20,InlineResponse20011DataUtxo,
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse20011Data
 */
export interface InlineResponse20011Data {

    /**
     * @type {string}
     * @memberof InlineResponse20011Data
     */
    address?: string;

    /**
     * @type {InlineResponse20011DataBrc20}
     * @memberof InlineResponse20011Data
     */
    brc20?: InlineResponse20011DataBrc20;

    /**
     * Only text type have this value
     *
     * @type {string}
     * @memberof InlineResponse20011Data
     */
    contentBody?: string;

    /**
     * @type {number}
     * @memberof InlineResponse20011Data
     */
    contentLength?: number;

    /**
     * @type {string}
     * @memberof InlineResponse20011Data
     */
    contentType?: string;

    /**
     * @type {number}
     * @memberof InlineResponse20011Data
     */
    height?: number;

    /**
     * @type {number}
     * @memberof InlineResponse20011Data
     */
    inSatoshi?: number;

    /**
     * @type {number}
     * @memberof InlineResponse20011Data
     */
    outSatoshi?: number;

    /**
     * @type {string}
     * @memberof InlineResponse20011Data
     */
    inscriptionId?: string;

    /**
     * @type {number}
     * @memberof InlineResponse20011Data
     */
    inscriptionIndex?: number;

    /**
     * @type {number}
     * @memberof InlineResponse20011Data
     */
    inscriptionNumber?: number;

    /**
     * @type {number}
     * @memberof InlineResponse20011Data
     */
    offset?: number;

    /**
     * @type {number}
     * @memberof InlineResponse20011Data
     */
    timestamp?: number;

    /**
     * @type {InlineResponse20011DataUtxo}
     * @memberof InlineResponse20011Data
     */
    utxo?: InlineResponse20011DataUtxo;
}
