/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse20042DataList } from './inline-response20042-data-list';
import {
    InlineResponse20042DataList,
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse20042Data
 */
export interface InlineResponse20042Data {

    /**
     * @type {number}
     * @memberof InlineResponse20042Data
     */
    total?: number;

    /**
     * @type {Array<InlineResponse20042DataList>}
     * @memberof InlineResponse20042Data
     */
    list?: Array<InlineResponse20042DataList>;
}
