/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse2009Data
 */
export interface InlineResponse2009Data {

    /**
     * @type {string}
     * @memberof InlineResponse2009Data
     */
    address?: string;

    /**
     * @type {number}
     * @memberof InlineResponse2009Data
     */
    satoshi?: number;

    /**
     * @type {number}
     * @memberof InlineResponse2009Data
     */
    pendingSatoshi?: number;

    /**
     * @type {number}
     * @memberof InlineResponse2009Data
     */
    utxoCount?: number;

    /**
     * @type {number}
     * @memberof InlineResponse2009Data
     */
    btcSatoshi?: number;

    /**
     * @type {number}
     * @memberof InlineResponse2009Data
     */
    btcPendingSatoshi?: number;

    /**
     * @type {number}
     * @memberof InlineResponse2009Data
     */
    btcUtxoCount?: number;

    /**
     * @type {number}
     * @memberof InlineResponse2009Data
     */
    inscriptionSatoshi?: number;

    /**
     * @type {number}
     * @memberof InlineResponse2009Data
     */
    inscriptionPendingSatoshi?: number;

    /**
     * @type {number}
     * @memberof InlineResponse2009Data
     */
    inscriptionUtxoCount?: number;
}
