/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BRC20InfoItem } from './brc20-info-item';
import {
    BRC20InfoItem,
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse20016
 */
export interface InlineResponse20016 {

    /**
     * @type {number}
     * @memberof InlineResponse20016
     */
    code?: InlineResponse20016CodeEnum;

    /**
     * @type {string}
     * @memberof InlineResponse20016
     * @example OK
     */
    msg?: string;

    /**
     * @type {BRC20InfoItem}
     * @memberof InlineResponse20016
     */
    data?: BRC20InfoItem;
}

/**
 * @export
 * @enum {string}
 */
export enum InlineResponse20016CodeEnum {
    NUMBER_0 = 0,
    NUMBER_MINUS_1 = -1
}

