/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse20033Data
 */
export interface InlineResponse20033Data {

    /**
     * Function id
     *
     * @type {string}
     * @memberof InlineResponse20033Data
     */
    id?: string;

    /**
     * The rollup inscription id where the function is located
     *
     * @type {string}
     * @memberof InlineResponse20033Data
     */
    rollupInscriptionId?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20033Data
     */
    address?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20033Data
     */
    tickIn?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20033Data
     */
    tickOut?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20033Data
     */
    amountIn?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20033Data
     */
    amountOut?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20033Data
     */
    exactType?: string;

    /**
     * @type {number}
     * @memberof InlineResponse20033Data
     */
    ts?: number;
}
