/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse20055Data
 */
export interface InlineResponse20055Data {

    /**
     * @type {string}
     * @memberof InlineResponse20055Data
     */
    bidId: string;

    /**
     * Bid psbt
     *
     * @type {string}
     * @memberof InlineResponse20055Data
     */
    psbtBid: string;

    /**
     * Auction mode is used, and the current empty string can be passed
     *
     * @type {string}
     * @memberof InlineResponse20055Data
     */
    psbtBid2?: string;

    /**
     * Auction mode is used, and the current empty string can be passed
     *
     * @type {string}
     * @memberof InlineResponse20055Data
     */
    psbtSettle?: string;

    /**
     * The service fee charged by the platform
     *
     * @type {number}
     * @memberof InlineResponse20055Data
     */
    serverFee: number;

    /**
     * BTC network total fee
     *
     * @type {number}
     * @memberof InlineResponse20055Data
     */
    networkFee: number;

    /**
     * BTC network fee rate
     *
     * @type {number}
     * @memberof InlineResponse20055Data
     */
    feeRate: number;

    /**
     * @type {number}
     * @memberof InlineResponse20055Data
     */
    nftValue: number;

    /**
     * Specifies the bid signature location used by the xverse wallet
     *
     * @type {Array<number>}
     * @memberof InlineResponse20055Data
     */
    bidSignIndexes?: Array<number>;
}
