/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse20020DataDetail } from './inline-response20020-data-detail';
import {
    InlineResponse20020DataDetail,
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse20020Data
 */
export interface InlineResponse20020Data {

    /**
     * @type {number}
     * @memberof InlineResponse20020Data
     */
    height?: number;

    /**
     * @type {number}
     * @memberof InlineResponse20020Data
     */
    start?: number;

    /**
     * @type {number}
     * @memberof InlineResponse20020Data
     */
    total?: number;

    /**
     * @type {Array<InlineResponse20020DataDetail>}
     * @memberof InlineResponse20020Data
     */
    detail?: Array<InlineResponse20020DataDetail>;
}
