/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse20012Data } from './inline-response20012-data';
import {
    InlineResponse20012Data,
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse20012
 */
export interface InlineResponse20012 {

    /**
     * @type {number}
     * @memberof InlineResponse20012
     */
    code?: InlineResponse20012CodeEnum;

    /**
     * @type {string}
     * @memberof InlineResponse20012
     * @example OK
     */
    msg?: string;

    /**
     * @type {InlineResponse20012Data}
     * @memberof InlineResponse20012
     */
    data?: InlineResponse20012Data;
}

/**
 * @export
 * @enum {string}
 */
export enum InlineResponse20012CodeEnum {
    NUMBER_0 = 0,
    NUMBER_MINUS_1 = -1
}

