/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse20025Data
 */
export interface InlineResponse20025Data {

    /**
     * Amount deposit on the day.
     *
     * @type {string}
     * @memberof InlineResponse20025Data
     */
    dailyAmount?: string;

    /**
     * Limit for the day.
     *
     * @type {string}
     * @memberof InlineResponse20025Data
     */
    dailyLimit?: string;

    /**
     * Recommended deposit amount.
     *
     * @type {string}
     * @memberof InlineResponse20025Data
     */
    recommendDeposit?: string;
}
