/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse20024DataBalance } from './inline-response20024-data-balance';
import {
    InlineResponse20024DataBalance,
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse20024Data
 */
export interface InlineResponse20024Data {

    /**
     * @type {InlineResponse20024DataBalance}
     * @memberof InlineResponse20024Data
     */
    balance?: InlineResponse20024DataBalance;

    /**
     * @type {string}
     * @memberof InlineResponse20024Data
     */
    decimal?: string;
}
