/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse20048DataMatchHistory
 */
export interface InlineResponse20048DataMatchHistory {

    /**
     * Withdraw inscription
     *
     * @type {string}
     * @memberof InlineResponse20048DataMatchHistory
     */
    approveInscriptionId?: string;

    /**
     * Deposit inscription
     *
     * @type {string}
     * @memberof InlineResponse20048DataMatchHistory
     */
    transferInscriptionId?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20048DataMatchHistory
     */
    tick?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20048DataMatchHistory
     */
    consumeAmount?: string;

    /**
     * Residual cash withdrawal
     *
     * @type {string}
     * @memberof InlineResponse20048DataMatchHistory
     */
    remainAmount?: string;

    /**
     * Withdraw user address
     *
     * @type {string}
     * @memberof InlineResponse20048DataMatchHistory
     */
    approveAddress?: string;

    /**
     * Deposit user address
     *
     * @type {string}
     * @memberof InlineResponse20048DataMatchHistory
     */
    transferAddress?: string;

    /**
     * Matching txid
     *
     * @type {string}
     * @memberof InlineResponse20048DataMatchHistory
     */
    txid?: string;

    /**
     * @type {number}
     * @memberof InlineResponse20048DataMatchHistory
     */
    ts?: number;
}
