/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse20039DataList
 */
export interface InlineResponse20039DataList {

    /**
     * @type {string}
     * @memberof InlineResponse20039DataList
     */
    type?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20039DataList
     */
    tick0?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20039DataList
     */
    tick1?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20039DataList
     */
    amount0?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20039DataList
     */
    amount1?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20039DataList
     */
    lp?: string;

    /**
     * @type {number}
     * @memberof InlineResponse20039DataList
     */
    ts?: number;
}
