/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse20017DataDetail
 */
export interface InlineResponse20017DataDetail {

    /**
     * @type {string}
     * @memberof InlineResponse20017DataDetail
     */
    address?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20017DataDetail
     */
    availableBalance?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20017DataDetail
     */
    overallBalance?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20017DataDetail
     */
    transferableBalance?: string;
}
