/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse20050DataList } from './inline-response20050-data-list';
import {
    InlineResponse20050DataList,
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse20050Data
 */
export interface InlineResponse20050Data {

    /**
     * @type {number}
     * @memberof InlineResponse20050Data
     */
    bTCPrice: number;

    /**
     * @type {Array<InlineResponse20050DataList>}
     * @memberof InlineResponse20050Data
     */
    list?: Array<InlineResponse20050DataList>;

    /**
     * @type {Array<InlineResponse20050DataList>}
     * @memberof InlineResponse20050Data
     */
    deploy?: Array<InlineResponse20050DataList>;

    /**
     * @type {Array<InlineResponse20050DataList>}
     * @memberof InlineResponse20050Data
     */
    cap?: Array<InlineResponse20050DataList>;
}
