/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse20040DataList
 */
export interface InlineResponse20040DataList {

    /**
     * Input tick
     *
     * @type {string}
     * @memberof InlineResponse20040DataList
     */
    tickIn: string;

    /**
     * Output tick
     *
     * @type {string}
     * @memberof InlineResponse20040DataList
     */
    tickOut: string;

    /**
     * The amount of input tick
     *
     * @type {string}
     * @memberof InlineResponse20040DataList
     */
    amountIn: string;

    /**
     * The amount of output tick
     *
     * @type {string}
     * @memberof InlineResponse20040DataList
     */
    amountOut: string;

    /**
     * @type {string}
     * @memberof InlineResponse20040DataList
     */
    exactType?: string;

    /**
     * @type {number}
     * @memberof InlineResponse20040DataList
     */
    ts?: number;
}
