/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse20022DataDetailData
 */
export interface InlineResponse20022DataDetailData {

    /**
     * @type {string}
     * @memberof InlineResponse20022DataDetailData
     */
    amt?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20022DataDetailData
     */
    decimal?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20022DataDetailData
     */
    lim?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20022DataDetailData
     */
    max?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20022DataDetailData
     */
    minted?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20022DataDetailData
     */
    op?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20022DataDetailData
     */
    tick?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20022DataDetailData
     */
    to?: string;
}
