/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse20052DataList } from './inline-response20052-data-list';
import {
    InlineResponse20052DataList,
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse20052Data
 */
export interface InlineResponse20052Data {

    /**
     * @type {Array<InlineResponse20052DataList>}
     * @memberof InlineResponse20052Data
     */
    list: Array<InlineResponse20052DataList>;

    /**
     * @type {number}
     * @memberof InlineResponse20052Data
     */
    total: number;

    /**
     * @type {number}
     * @memberof InlineResponse20052Data
     */
    timestamp?: number;
}
