/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse20046Data
 */
export interface InlineResponse20046Data {

    /**
     * The withdraw order id
     *
     * @type {string}
     * @memberof InlineResponse20046Data
     */
    id?: string;

    /**
     * The user psbt with payment
     *
     * @type {string}
     * @memberof InlineResponse20046Data
     */
    paymentPsbt?: string;

    /**
     * The user psbt with approve insctiption
     *
     * @type {string}
     * @memberof InlineResponse20046Data
     */
    approvePsbt?: string;

    /**
     * @type {number}
     * @memberof InlineResponse20046Data
     */
    networkFee?: number;

    /**
     * User signature information
     *
     * @type {string}
     * @memberof InlineResponse20046Data
     */
    signMsg?: string;

    /**
     * Number of bytes on L1 chain
     *
     * @type {number}
     * @memberof InlineResponse20046Data
     */
    bytesL1?: number;

    /**
     * Number of bytes on L1 chain
     *
     * @type {number}
     * @memberof InlineResponse20046Data
     */
    bytesL2?: number;

    /**
     * Bitcoin network fee rate
     *
     * @type {string}
     * @memberof InlineResponse20046Data
     */
    feeRate?: string;

    /**
     * L2 cost per byte
     *
     * @type {string}
     * @memberof InlineResponse20046Data
     */
    gasPrice?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20046Data
     */
    serviceFeeL1?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20046Data
     */
    serviceFeeL2?: string;

    /**
     * L1 USD price per sats
     *
     * @type {string}
     * @memberof InlineResponse20046Data
     */
    unitUsdPriceL1?: string;

    /**
     * L2 USD price per sats
     *
     * @type {string}
     * @memberof InlineResponse20046Data
     */
    unitUsdPriceL2?: string;

    /**
     * The user's remainin L2 sats balance
     *
     * @type {string}
     * @memberof InlineResponse20046Data
     */
    serviceTickBalance?: string;
}
