/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse20023Data
 */
export interface InlineResponse20023Data {

    /**
     * @type {string}
     * @memberof InlineResponse20023Data
     */
    moduleId?: string;

    /**
     * The tick used for the second layer gas.
     *
     * @type {string}
     * @memberof InlineResponse20023Data
     */
    serviceGasTick?: string;

    /**
     * Number of confirmations required for direct deposit.
     *
     * @type {number}
     * @memberof InlineResponse20023Data
     */
    pendingDepositDirectNum?: number;

    /**
     * Number of confirmations required for matching deposit.
     *
     * @type {number}
     * @memberof InlineResponse20023Data
     */
    pendingDepositMatchingNum?: number;
}
