/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OrderCreateParamsFiles } from './order-create-params-files';
import {
    OrderCreateParamsFiles,
} from ".";

/**
 * 
 *
 * @export
 * @interface OrderCreateParams
 */
export interface OrderCreateParams {

    /**
     * Bitcoin address to receive the inscriptions
     *
     * @type {string}
     * @memberof OrderCreateParams
     */
    receiveAddress?: string;

    /**
     * The fee rate of transaction
     *
     * @type {number}
     * @memberof OrderCreateParams
     * @example 1
     */
    feeRate?: number;

    /**
     * The balance of inscription
     *
     * @type {number}
     * @memberof OrderCreateParams
     * @example 546
     */
    outputValue?: number;

    /**
     * @type {Array<OrderCreateParamsFiles>}
     * @memberof OrderCreateParams
     * @example [{"filename":"1000.sats","dataURL":"data:text/plain;charset=utf-8;base64,eyJwIjoic25zIiwib3AiOiJyZWciLCJuYW1lIjoiMTAwMDAuc2F0cyJ9"}]
     */
    files?: Array<OrderCreateParamsFiles>;

    /**
     * Developer address to receive extra fee
     *
     * @type {string}
     * @memberof OrderCreateParams
     */
    devAddress?: string;

    /**
     * Extra fee to pay to developer's address
     *
     * @type {number}
     * @memberof OrderCreateParams
     */
    devFee?: number;
}
