/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface TxHistoryItem
 */
export interface TxHistoryItem {

    /**
     * @type {string}
     * @memberof TxHistoryItem
     */
    txid?: string;

    /**
     * @type {number}
     * @memberof TxHistoryItem
     */
    nIn?: number;

    /**
     * @type {number}
     * @memberof TxHistoryItem
     */
    nOut?: number;

    /**
     * @type {number}
     * @memberof TxHistoryItem
     */
    inSatoshi?: number;

    /**
     * @type {number}
     * @memberof TxHistoryItem
     */
    outSatoshi?: number;

    /**
     * @type {number}
     * @memberof TxHistoryItem
     */
    locktime?: number;

    /**
     * @type {number}
     * @memberof TxHistoryItem
     */
    size?: number;

    /**
     * @type {number}
     * @memberof TxHistoryItem
     */
    witOffset?: number;

    /**
     * @type {number}
     * @memberof TxHistoryItem
     */
    height?: number;

    /**
     * @type {number}
     * @memberof TxHistoryItem
     */
    idx?: number;

    /**
     * @type {string}
     * @memberof TxHistoryItem
     */
    blkid?: string;

    /**
     * @type {number}
     * @memberof TxHistoryItem
     */
    confirmations?: number;

    /**
     * @type {number}
     * @memberof TxHistoryItem
     */
    timestamp?: number;
}
