/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InscriptionItem } from './inscription-item';
import {
    InscriptionItem,
} from ".";

/**
 * 
 *
 * @export
 * @interface UTXO
 */
export interface UTXO {

    /**
     * @type {string}
     * @memberof UTXO
     */
    address?: string;

    /**
     * @type {number}
     * @memberof UTXO
     */
    codeType?: number;

    /**
     * @type {number}
     * @memberof UTXO
     */
    height?: number;

    /**
     * @type {number}
     * @memberof UTXO
     */
    idx?: number;

    /**
     * @type {Array<InscriptionItem>}
     * @memberof UTXO
     */
    inscriptions?: Array<InscriptionItem>;

    /**
     * @type {boolean}
     * @memberof UTXO
     * @example false
     */
    isOpInRBF?: boolean;

    /**
     * @type {number}
     * @memberof UTXO
     * @example 10000
     */
    satoshi?: number;

    /**
     * @type {string}
     * @memberof UTXO
     */
    scriptPk?: string;

    /**
     * @type {string}
     * @memberof UTXO
     */
    scriptType?: string;

    /**
     * @type {string}
     * @memberof UTXO
     */
    txid?: string;

    /**
     * @type {number}
     * @memberof UTXO
     * @example 0
     */
    vout?: number;
}
