/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface V3markettypeauctionlistSort
 */
export interface V3markettypeauctionlistSort {

    /**
     * @type {number}
     * @memberof V3markettypeauctionlistSort
     */
    unitPrice?: V3markettypeauctionlistSortUnitPriceEnum;

    /**
     * @type {number}
     * @memberof V3markettypeauctionlistSort
     */
    onSaleTime?: V3markettypeauctionlistSortOnSaleTimeEnum;

    /**
     * @type {number}
     * @memberof V3markettypeauctionlistSort
     */
    initPrice?: V3markettypeauctionlistSortInitPriceEnum;

    /**
     * @type {number}
     * @memberof V3markettypeauctionlistSort
     */
    inscriptionNumber?: V3markettypeauctionlistSortInscriptionNumberEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum V3markettypeauctionlistSortUnitPriceEnum {
    NUMBER_1 = 1,
    NUMBER_MINUS_1 = -1
}
/**
 * @export
 * @enum {string}
 */
export enum V3markettypeauctionlistSortOnSaleTimeEnum {
    NUMBER_1 = 1,
    NUMBER_MINUS_1 = -1
}
/**
 * @export
 * @enum {string}
 */
export enum V3markettypeauctionlistSortInitPriceEnum {
    NUMBER_1 = 1,
    NUMBER_MINUS_1 = -1
}
/**
 * @export
 * @enum {string}
 */
export enum V3markettypeauctionlistSortInscriptionNumberEnum {
    NUMBER_1 = 1,
    NUMBER_MINUS_1 = -1
}

