/* tslint:disable */
/* eslint-disable */
/**
 * UniSat Wallet - OpenAPI
 * This is UniSat Wallet Open API. If you wish to use the OpenAPI, please feel free to send us an email, and we will provide you with an API KEY.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@unisat.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface V3markettypeauctionactionsFilter
 */
export interface V3markettypeauctionactionsFilter {

    /**
     * @type {string}
     * @memberof V3markettypeauctionactionsFilter
     */
    nftType?: V3markettypeauctionactionsFilterNftTypeEnum;

    /**
     * @type {string}
     * @memberof V3markettypeauctionactionsFilter
     */
    address?: string;

    /**
     * @type {string}
     * @memberof V3markettypeauctionactionsFilter
     */
    inscriptionId?: string;

    /**
     * Event type: Cancel, Listed, Sold, Updated
     *
     * @type {string}
     * @memberof V3markettypeauctionactionsFilter
     */
    event?: V3markettypeauctionactionsFilterEventEnum;

    /**
     * @type {string}
     * @memberof V3markettypeauctionactionsFilter
     */
    tick?: string;

    /**
     * @type {string}
     * @memberof V3markettypeauctionactionsFilter
     */
    domainType?: string;

    /**
     * @type {string}
     * @memberof V3markettypeauctionactionsFilter
     */
    collectionId?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum V3markettypeauctionactionsFilterNftTypeEnum {
    Brc20 = 'brc20',
    Collection = 'collection',
    Domain = 'domain'
}
/**
 * @export
 * @enum {string}
 */
export enum V3markettypeauctionactionsFilterEventEnum {
    Cancel = 'Cancel',
    Claim = 'Claim',
    Listed = 'Listed',
    Sold = 'Sold',
    Updated = 'Updated'
}

